// Register
POST http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "Samir Hussein",
    "username": "samir377",
    "email": "samirhussein377@gmail.com",
    "password": "samir123"
}

// Login
###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "mayahussein377@gmail.com",
    "password": "maya123"
}

// Create a post
###
POST http://localhost:5000/api/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTE0MjczN2M0MTJhYjYzMmJjZmJhOCIsImlhdCI6MTY5MjUyNDczOX0.p93rc_4uXG8AMX9LSjmmrbykdVoJ6YDyFZGn2oz3D6U

{
    "title": "Book Three",
    "author": "John",
    "picture": "pic1.jpg"
}

// Follow a user
###
PUT http://localhost:5000/api/users/64e09d381d3bacbdd96525e8/follow
Content-Type: application/json

{
    "userId": "64e0c3bcb1561babe956c7b5"
}

// Unfollow a user
###
PUT http://localhost:5000/api/users/64e0c3bcb1561babe956c7b5/unfollow
Content-Type: application/json

{
    "userId": "64e09d381d3bacbdd96525e8"
}

// Following Books
###
GET http://localhost:5000/api/books/64e0c3bcb1561babe956c7b5

// Like a book
###
PUT http://localhost:5000/api/books/64e0b33dd803462538b09797/like
Content-Type: application/json

{
    "userId": "64e09d381d3bacbdd96525e8"
}

// Search for books 
###
GET http://localhost:5000/api/books/search/john